config/routes.rb
Rails.application.routes.draw do

  root to: "static_pages#root"

  get "/stats", to: "static_pages#stats"
  get "/history", to: "static_pages#history"
  get "/media", to: "static_pages#media"
  get "/contact", to: "static_pages#contact"
  get "/admin", to: "static_pages#admin"


  resources :teams do
    resources :players
  end

end

app/models/player.rb
class Player < ActiveRecord::Base
  validates :name, :team_id, presence: true
  validates :name, uniqueness: { scope: :team_id,
    message: "already a player by that name on this team"}

  belongs_to :team


  def height
    self.height_feet.to_s + "\' " + self.height_inches + "\""
  end

end

app/models/team.rb
class Team < ActiveRecord::Base
  validates :name, :year, presence: true
  validates :name, uniqueness: true

  has_many :players

# What does this even mean?
  accepts_nested_attributes_for :players

# Got this from http://media.pragprog.com/titles/fr_arr/multiple_models_one_form.pdf

  # def add_player_link(name)
  #   link_to_function name do |page|
  #     page.insert_html :bottom, :players, partial: 'task', object: Player.new
  #   end
  # end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def create
    @team = Team.find(params[:id])
    @player = @team.players.new(player_params)

    if @team.save
      render @team
    else
      flash[:notice].errors = @player.errors.full_messages
      redirect_to team_url @team
    end
  end

  def show
    @player = Team.find(params[:id])
    render :show
  end

  def update
    @player = Team.find(params[:id])

    if @player.update(player_params)
      render :show
    else
      flash[:notice].errors = @player.errors.full_messages
      redirect_to team_player_url @player
    end
  end

  def destroy
  end

  private

    def player_params
      params.require(:player).permit(:name, :affiliation,
        :height_feet, :height_inches, :url)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def root
  end

  def stats
  end

  def history
  end

  def media
  end

  def contact
  end

  def admin

  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
    @teams = Team.where(year: Time.now.year)
  end

  def new
    @team = Team.new
    # Not sure if this is right
    @team.players.build
  end

  def create
    players_attrs = team_params.delete(:players_attributes)
    @team = Team.new(year: Time.now.year)

    # rescue any errors?
    @team.update(team_params)

    players_attrs.values.each do |player_attrs|

      # rescue any errors?
      player = @team.players.create(player_attrs)
    end
    render :show
  end

  def show
    @team = Team.find(params[:id])
    render :show
  end

  def edit
    @team = Team.find(params[:id])
    render :edit
  end

  def update
    @team = Team.find(params[:id])

    if @team.update(team_params)
      render :show
    else
      redirect_to team_url(@team)
    end
  end

  def destroy
    @team = Team.find(params[:id])
    @team.destroy
    render :index
  end

  private

    def team_params
      params.require(:team).permit!
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SFProAm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body class="<%= controller_name %> <%= action_name %>">
  <%= yield %>
  <%= yield :javascript %>
</body>

</html>

app/views/players/_new_player_input.html.erb
<div id="new-player-input">
  <%= f.fields_for :players do |player_f| %>
    <%= player_f.label :name, "Player Name:" %>
    <%= player_f.text_field :name %>
    <br>
    <%= player_f.label :affiliation, "Team Affiliation (St. Mary's, D-League, Europe, etc.):" %>
    <%= player_f.text_field :affiliation %>
  <% end %>
  <br><br>
</div>

app/views/static_pages/admin.html.erb
<h1>Admin</h1>

<label>Username
  <input type="text" name="username" value="">
</label>

<label>Password
  <input type="password" name="password" value="">
</label>


<a href="/">Home</a>

app/views/static_pages/root.html.erb
<h1>San Francisco Bay Area Pro Am Basketball League</h1>

<a href="<%= teams_url %>">Teams</a>
<a href="<%= stats_url %>">Stats</a>
<a href="<%= history_url %>">History</a>
<a href="<%= media_url %>">Media</a>
<a href="<%= contact_url %>">Contact</a>



<a href="/admin">Admin</a>